language: python

dist: focal

matrix:
  include:
   - os: linux
     arch: ppc64le
   - os: linux
     arch: s390x
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - pip install --no-cache-dir -r requirements-test.txt

script:
  - make test
