name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: black
        run: |
          make black
        continue-on-error: true
      - name: flake8
        run: |
          make flake8
        continue-on-error: true
      - name: pylint
        run: |
          make pylint
      - name: test
        run: |
          make test
      - name: mypy
        run: |
          make mypy
  run:
    runs-on: ubuntu-latest
    name: codecov
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-test.txt
      - name: Run tests and collect coverage
        run: make pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
